# Generated by Django 6.0.2 on 2026-04-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
