# Generated by Django 6.0.4 on 2026-05-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proj1App", "0004_community_post_community_communitymembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
